version: '3.8'
services:
  photo-analyser:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181
    networks:
      - shared_network

networks:
  shared_network:
    external: true